### PR TITLE
Pr 744 try 2

### PR DESCRIPTION
**Pull request by mceachen**
See PR #744

### CODE REVIEW

**Comment by mceachen** [comment]
To recap: Joe refactored the QueryBuilder to capture the incoming and outgoing model types, so many methods on QueryBuilder that used to only be correct at the end of the call chain can now work in the middle of the chain.

Note that this *does contain some breaking changes*, in that a number of interfaces were collapsed into the main `QueryBuilder` interface, and code that may have compiled in the past needs explicit casting or will expose prior defects. I've tried this branch against my project (which uses ~75% of the objection API surface area), and it did require a couple updates, but the changes to my project were minimal.

**Comment by jtlapp** [comment]
Oh, don't forget that this resolves #742 and partially resolves #717. I never looked at how to accommodate the varying `relate()` output types of #717.

**Comment by mceachen** [comment]
@koskimas I've run this with the new tests from #735 and everything passes. Are you OK merging this?

**Comment by koskimas** [comment]
Looks good to me! Great job with this 👍

**Comment by jtlapp** [comment]
Just FYI, these new typings break my [rigging for Typescript support of custom query builders](https://github.com/jtlapp/temp-qb). The rigging is not viable for publication, but the break does send me off looking for another way to get custom query builders working. The problem appears to have to do with defaulting the result type to `Model[]`. I don't know if the fix is in my rigging or in the way the typings handle the defaulting.

Investigating...

**Comment by elhigu** [comment]
In my current project these lines started failing: 

```
throw new ValidationError({docType: 'Invalid document type'});

file: 'file:///Users/mikaelle/Projects/Vincit/xxx/index.ts'
severity: 'Error'
message: 'Argument of type '{ name: string; }' is not assignable to parameter of type 'CreateValidationErrorArgs'.
  Object literal may only specify known properties, and 'name' does not exist in type 'CreateValidationErrorArgs'.'
at: '92,34'
source: 'ts'
code: '2345'
```

**Comment by jtlapp** [comment]
I solved my problem in the custom query implementation. Each query builder class must specify the default model array. E.g.:

```ts
export class SessionQueryBuilder<QM, RM=QM[], RV=RM> extends QueryBuilder<QM, RM, RV> {
  session(session: Session) {
    return this.mergeContext({
      session: session
    });
  }
}
```

So all is good on that front. I'll still look at how to get support for custom query builders into the typings proper.

**Comment by jtlapp** [comment]
>In my current project these lines started failing:
>
>throw new ValidationError({docType: 'Invalid document type'});

@elhigu, I'm thinking that the relevant mods are from the work @koskimas did on #501.

**Comment by koskimas** [comment]
@elhigu Those are 1.0 breaking changes.

**Comment by koskimas** [comment]
I just realized that the new validation error types don't allow custom error types or even a `Generic` or `Custom` type to use for own validation errors. Maybe something like that should be added. It's not related to this PR. I'll create another one if I come up with a solution.

**Comment by jtlapp** [comment]
@mceachen, transactions are yielding `Promise<any>`. Not fully understanding how they are supposed to behave, it's hard for me to think about how we might do better than this.

**Comment by jtlapp** [comment]
Type inference works fine with `Objection.transaction()`, but there's still something odd.

The typings declare a transaction to be the following but never uses the `T` type:

```ts
  export interface transaction<T> {
```

Here's the only place the decl is used, on the Objection namespace, apparently having no effect:

```ts
  export const transaction: transaction<any>;
```

This state of affairs also exists in the typings prior to the result type pass-through mods.

(I may have mistakenly interpreted this as meaning that transactions only return type `any`.)

**Comment by mceachen** [comment]
@jtlapp let's not conflate other typings with this PR. I've merged this just now, and we can talk transactions over hangouts and determine what we should do there.

**Pull request merged**
