### PR TITLE
Update returning-tricks comments

### PR DESCRIPTION
**Pull request by vladshcherbin**
It's hard to understand current construction (however many), especially for a non-native English speaker. *However* is usually used for a different purpose.

Proposal to change it to a more common one.

### CODE REVIEW

**Comment by koskimas** [comment]
Thanks! Will merge this as soon as i find time to figure out what's up with the CI

**Comment by koskimas** [comment]
@vladshcherbin Could you rebase this on top of master where the CI is fixed?

**Comment by vladshcherbin** [comment]
@koskimas sure, now ci passes :)

**Comment by koskimas** [comment]
Thanks!

**Pull request merged**
