### PR TITLE
Security Fix for Prototype Pollution in v1

### PR DESCRIPTION
**Pull request by rtteal**
Fix prototype pollution when path components are not strings

### CODE REVIEW

**Comment by rtteal** [comment]
Hi @koskimas, can this be merged?

**Comment by lehni** [comment]
@koskimas was quite clear on prototype pollution fixes in his comment here: https://github.com/Vincit/objection.js/issues/2261#issuecomment-1100117833

Is there a scenario where the above code could actually become an attack vector?

**Comment by lehni** [comment]
The referenced function has since been changed to use `isSafeKey()`, which checks for `__proto__`. This PR thus doesn't need merging anymore.

**Comment by lehni** [comment]
Actually, the fix was already in place before the PR was submitted, and thus the PR was never needed nor did it change anything: https://github.com/Vincit/objection.js/commit/867dc46537a8536578556e4b25b2add411f2a5e5

@koskimas was quite clear on his opinion on prototype pollution also, which he outlined here:

https://github.com/Vincit/objection.js/issues/2261#issuecomment-1100117833

**Pull request closed without merging**
