### PR TITLE
add multi-schema integration tests for Postgres

### PR DESCRIPTION
**Pull request by heisian**

### CODE REVIEW

**Comment by koskimas** [comment]
Awesome! Thanks!

**Comment by koskimas** [comment]
@heisian The tests don't pass

**Comment by koskimas** [comment]
```

  1) integration tests
       postgres
         related tables across non-public postgres schemas
           simple find query (child):
      Error: expected [ { id: 1, name: 'Fluffy', ownerId: 1 } ] to sort of equal [ { id: 1, name: 'Fluffy' } ]
      + expected - actual
       [
         {
           "id": 1
           "name": "Fluffy"
      -    "ownerId": 1
         }
       ]
      
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.eql (node_modules/expect.js/index.js:230:10)
      at Animal.query.then.animals (tests/integration/schema.js:246:30)
  From previous event:
      at QueryBuilder.then (lib/queryBuilder/QueryBuilder.js:9:23926)
      at Context.it (tests/integration/schema.js:245:43)
  From previous event:
  2) integration tests
       postgres
         related tables across non-public postgres schemas
           columnInfo:
      Error: expected { id: 
   { type: 'integer',
     maxLength: null,
     nullable: false,
     defaultValue: 'nextval(\'"homoSapiens"."Person_id_seq"\'::regclass)' },
  name: 
   { type: 'character varying',
     maxLength: 255,
     nullable: true,
     defaultValue: null } } to sort of equal { id: 
   { type: 'integer',
     maxLength: null,
     nullable: false,
     defaultValue: 'nextval(\'"Person_id_seq"\'::regclass)' },
  name: 
   { type: 'character varying',
     maxLength: 255,
     nullable: true,
     defaultValue: null } }
      + expected - actual
       {
         "id": {
      -    "defaultValue": "nextval('\"homoSapiens\".\"Person_id_seq\"'::regclass)"
      +    "defaultValue": "nextval('\"Person_id_seq\"'::regclass)"
           "maxLength": [null]
           "nullable": false
           "type": "integer"
         }
      
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.eql (node_modules/expect.js/index.js:230:10)
      at Person.query.columnInfo.then.info (tests/integration/schema.js:300:29)
  From previous event:
      at Builder.Target.then (node_modules/knex/lib/interface.js:40:24)
      at Context.it (tests/integration/schema.js:298:12)
  From previous event:
```

**Comment by heisian** [comment]
I know, went out to lunch. Haven't been able to get the tests locally to connect to my postgres server so I've just been using Travis CI to debug. Should pass in a commit or two :P

**Comment by heisian** [comment]
6th time's the charm ;)

**Pull request merged**
