### PR TITLE
Add onVal (and related operations) to JoinBuilder

### PR DESCRIPTION
**Pull request by rsanchez**
Version 0.16.1 of Knex added onVal method(s) to the join clause builder (https://github.com/tgriesser/knex/pull/2746). This PR brings support for these new methods in Objection's JoinBuilder.

### CODE REVIEW

**Comment by koskimas** [comment]
@rsanchez The tests fail because some of the methods are not found in knex.

**Comment by koskimas** [comment]
Closing for lack of response.

**Comment by kibertoad** [comment]
Let me take a look at this one.

**Comment by kibertoad** [comment]
@koskimas The scariest part of this seems to be that compatibility with latest knex in general is broken, and this wasn't noticed since we cache our dependencies and newer version never got picked up.

**Pull request merged**
