### PR TITLE
Fix #652

### LINKED ISSUE #652: I cannot get the express-ts example to work as is
When I run npm start I get:

> objection-example-express-ts@0.7.0 start /Users/mike/workspace/node/objection.js/examples/express-ts
> tsc && node lib/app.js

../../typings/objection/index.d.ts(6,23): error TS2307: Cannot find module 'knex'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! objection-example-express-ts@0.7.0 start: `tsc && node lib/app.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the objection-example-express-ts@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2017-12-09T23_01_56_645Z-debug.log

### PR DESCRIPTION
**Pull request by mceachen**
* Example now requires the published version of objection rather than the local build.
* Ran `salita -u && yarn upgrade` to upgrade typescript related deps.

### CODE REVIEW

**Comment by mceachen** [comment]
@koskimas the tests are failing in eslint due to unrelated files, I fixed that in #656.

I'm a bit concerned that this fix might actually just be hiding the fact that there's a new bug in the typings. I'll run my project against master and make sure master is still in good shape.

**Comment by koskimas** [comment]
LGTM. I tried to use the github's mergetool to resolve the conflicts, but I seem ti have generated two merge commits that don't fix the conflicts 😄 Never again.

**Comment by koskimas** [comment]
And thank you once again!

**Comment by mceachen** [comment]
FWIW I think there's something funky going on with the current version of eslint in package.json. Windows and linux hang indefinitely when I `yarn eslint`.

**Pull request merged**
