### PR TITLE
Test to illustrate problem with children instantiation

### PR DESCRIPTION
**Pull request by igor-savin-ht**
refs: #777

### CODE REVIEW

**Comment by koskimas** [comment]
If you run `npm run prettier` and add `it.skip` I can merge this instead of copy-pasting

**Comment by igor-savin-ht** [comment]
@koskimas Done!

**Comment by koskimas** [comment]
Thank you!

**Comment by koskimas** [comment]
Prettier was needed so that tests pass. Travis runs eslint that checks for prettier formatting.

**Comment by igor-savin-ht** [comment]
Prettier is amazing, actually, switching between formatting styles of different projects is nightmare without it :)

**Pull request merged**
