### PR TITLE
Security Fix for Prototype Pollution

### PR DESCRIPTION
**Pull request by ready-research**
Fix prototype pollution reported in https://www.huntr.dev/bounties/c98e0f0e-ebf2-4072-be73-a1848ea031cc/

### CODE REVIEW

**Comment by ready-research** [comment]
@koskimas Can you please confirm the same in hunr by validating and submitting the fix as well. Thank you.

**Comment by calvinl** [comment]
Hi, we use objection in production and we're seeing this issue come up in with Dependabot alerts, but there is no patched version available. Will this patch be in 2.x released or just planned for v3?

**Comment by koskimas** [comment]
2.2.16 contains the fix, but you'll probably still get the alert since the CVE is not resolved. I'm trying to find out how to resolve it.

**Comment by koskimas** [comment]
@ready-research Could you help me out here? What do I need to do to? I cherry picked this fix to the [v2](https://github.com/Vincit/objection.js/commits/v2) branch. [here's](46b842a6bc897198b83f41ac85c92864b991d7e9) the cherry-picked commit in that branch.

**Comment by ready-research** [comment]
@koskimas Jamie added a comment in huntr advisory. Please coordinate with him. Thank you.

**Comment by pvatterott** [comment]
Can this be cherry-picked to v1 as well?

**Pull request merged**
