### PR TITLE
typings: Remove generic type from Transaction

### LINKED ISSUE #455: Generic Transaction
With the new update, the Transaction became a generic type, but its broken all my code, see the example below:

image

I can't use the same transaction for two different queries and it create a idea that is not possible.

### PR DESCRIPTION
**Pull request by danieloprado**
Fix #455

### CODE REVIEW

**Comment by elhigu** [comment]
Should there be a regression test case added for #455 to https://github.com/Vincit/objection.js/blob/master/tests/ts/examples.ts

**Comment by koskimas** [comment]
The examples.ts file is not even ran with the tests at the moment. PR to fix that too would be welcome

**Comment by danieloprado** [comment]
Ok I will add this file to the test

**Comment by danieloprado** [comment]
Any updates?

**Comment by koskimas** [comment]
Thank you! One more thing: `commit` and `rollback` return promises, not QueryBuilders. I know this wasn't your mistake, but could you fix that while you're at it? Then I'm ready to merge this.

**Comment by danieloprado** [comment]
No problem!

**Comment by danieloprado** [comment]
I merged #458 to this pull request too

**Pull request merged**
