### PR TITLE
Node 14 development

### PR DESCRIPTION
**Pull request by kjs3**
Node 14 has an issue connecting to Postgres with `pg` versions below `8.3.0` which breaks the `setup-test-db.js` script.

This PR bumps the local dep for `pg` to `8.3.0` and `knex` to `0.21.5` (which relies on pg@8.3.0) so you can develop Objection locally using Node 14.

Tests pass with Node `10.22.0`, `12.18.3`, and `14.7.0`

### CODE REVIEW

**Comment by kibertoad** [comment]
Give me a sec to release 0.21.6 prior to merging this :)

**Comment by kibertoad** [comment]
Could you please bump to 0.21.6? Quite annoying noise was addressed in this one.

**Comment by kibertoad** [comment]
Can you also add Node 14 to the test matrix?

**Comment by kjs3** [comment]
@kibertoad: Bumped Knex to 0.21.6 and added Node 14 to Travis setup.

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
