### PR TITLE
Patch validator must keep required with discriminator

### PR DESCRIPTION
**Pull request by kapouer**
JSON Schema's OpenAPI specification allows some sort of schema inheritance:
https://ajv.js.org/json-schema.html#discriminator

To support this, objection's ajv "patch" validator should keep `required` field when it sits next a `discriminator` keyword.

To keep the change minimal, `ajvNoDefaults.opts.discriminator` is not checked to know if there is actual support for that keyword.

### CODE REVIEW

**Comment by kapouer** [comment]
Force-pushed to fix it.

**Comment by lehni** [comment]
LGT, thanks!

**Comment by kapouer** [comment]
Much appreciated

**Comment by lehni** [comment]
Released in v3.0.5

**Pull request merged**
