### PR TITLE
Unleash ajv to set defaults and manage compiled schema cache

### PR DESCRIPTION
**Pull request by kapouer**
I took the opportunity to enable v5 (see also #241) as well.
Fixes: #243.

I suspect this might not be mergeable "as is" but it's a starting point.

### CODE REVIEW

**Comment by koskimas** [comment]
The own caching was there for a reason. For the 99% case where the schema never changed the compiled function was cached directly. The changing schema cache was also alot faster than AJV's because I used JSON.stringify. I don't think we should remove that. Also the tests fail.

**Comment by kapouer** [comment]
The test failure
> Error: Could not connect to postgres. Make sure the server is running and the database objection_test is created.
doesn't seem to be related to what i changed.

Oh - then ajv's choice of not using JSON.stringify seems odd.
Isn't JSON.stringify not deterministic today ? I'll ask there.

**Comment by koskimas** [comment]
I think `JSON.stringify` is not used so that `{a: 1, b: 2}` and `{b: 2, a: 1}` hit the same cache. In our case that doesn't matter. The most important tweak is the 99% case I mentioned that doesn't serialize the schema at all.

**Comment by kapouer** [comment]
Right, then extra care must be added when updating ajv, since it caches compiled schemas by default - voiding the optimization you made to avoid extra stringification.

**Comment by kapouer** [comment]
Another small thing to mention: https://github.com/nickyout/fast-stable-stringify seems a bit better maintained and faster. I also ran a quick jsperf and it seems it's 60% slower than native JSON.stringify.
https://jsperf.com/fastjson (but the js file is hosted on non-ssl url, making chrome complain).

**Comment by kapouer** [comment]
Rebased, now all tests pass.

**Comment by koskimas** [comment]
Thanks!

**Pull request merged**
