### PR TITLE
Write docs and tests for QueryBuilder.clear()

### PR DESCRIPTION
**Pull request by lehni**
Similar to #758, here the docs and tests for QueryBuilder.clear()

### CODE REVIEW

**Comment by kapouer** [comment]
Everybody's going to ask "does it clear select as well" ?

**Comment by koskimas** [comment]
@kapouer I think you misunderstood what the method does.

```js
// Clears all calls to `where` method.
builder.clear('where')
// Clears all calls to `select` method.
builder.clear('select')
// Clears all calls to `where`, `orWhere`, `andWhere` etc. method.
builder.clear(/where/)
```

**Comment by koskimas** [comment]
I think the documentation is clear on this.

**Comment by lehni** [comment]
I could add an example to illustrate the use of a regular expression though?

**Pull request merged**
