### PR TITLE
Use babel preset instead of explicit plugin installation

### PR DESCRIPTION
**Pull request by afm-sayem**
Instead of explicitly declaring each es2015 plugins, a preset can be used that contains all the plugins necessary for compiling to es2015.

### CODE REVIEW

**Comment by afm-sayem** [comment]
Build is failing for node v0.12. Is anyone using v0.12 to build objection.js?

**Comment by koskimas** [comment]
Is there a reason for this other than simpler package.json? The plugins are listed separately for two reasons.

1. I'm only including plugins I use.
2. I'm passing extra options for some plugins.

The first reason is not important, but the second one is. I'm telling Babel to generate faster inheritance code that ignores some corner cases. If this setting still works, I will merge this.

**Comment by afm-sayem** [comment]
I have checked this on node v6.0 and was able to build using `build.js` and run unit and integration tests. I just ran a diff between generated code pre and post patch and there was no change.

**Comment by koskimas** [comment]
All tests need to pass. I'm not dropping three versions for this tiny change.

**Comment by afm-sayem** [comment]
Far I understand, this doesn't impact anyone installing the library since the changes are in dev-dependencies. If maintaining build in pre node v5 is important then I don't think this should be merged.

**Comment by koskimas** [comment]
Keeping the travis tests working pre 0.12 is important. Also you haven't yet told me the reason for this change. What does this fix?

**Comment by afm-sayem** [comment]
This simplifies package.json and the build file. Not a fix.

Since travis tests will fail for the changes made. I'm closing this.

**Pull request closed without merging**
