### PR TITLE
Add types for .mixin and .compose

### PR DESCRIPTION
**Pull request by mceachen**
Addresses https://github.com/Vincit/objection.js/issues/536

* added `.compose` and `.mixin` support. YIKES THAT IS SOME UGLY COPYPASTA but that's how you do it, afaik.
* removed unnecessary `this` capture from `.knexQuery` typing
* updated typings and typescript. @koskimas you might want to upgrade the other root package.json deps, many are not on the latest version (`yarn upgrade --latest`).
* added missing semis that tslint grumped about
* added assertions based on @drew-r's concerns (Drew, could you check this diff, because it seems like things are working as expected? I think I'm misunderstanding you, perhaps?)

### CODE REVIEW

**Comment by koskimas** [comment]
@mceachen `compose` and `mixin` don't take model classes, but only mixin functions. A mixin function is  a function that takes a model class as an argument and returns an anonymous subclass of the input. 

```js
const plugin1 = (Model) => {
  return class extends Model {
    foo() {
      console.log('foo');
    }
  }
}

const plugin2 = (Model) => {
  return class extends Model {
    bar() {
      console.log('bar');
    }
  }
}

const BaseModel1 = mixin(Model, [plugin1, plugin2]);
const BaseModel2 = mixin(Model, plugin1, plugin2);

const plugin1AndPlugin2 = compose(plugin1, plugin2);
const BaseModel3 = plugin1Plugin2(Model);
const BaseModel4 = mixin(Model, plugin1Plugin2);

class Person extends BaseModel1 {

}

const p = new Person();
p.foo();
p.bar();
```

**Comment by mceachen** [comment]
Thanks for those examples.

If I just look at those, it seems that you expect `.compose` to only takes plugins, and `.mixin` calls to always starts with `Model`. Is that correct?

I don't understand what you mean by "mixin don't take model classes," because every mixin example you have has a Model in the first position. Do you mean you expect them to take Model subclasses?

Plugins only accept Model classes, correct?

Thanks for being patient with my questions!

**Comment by mceachen** [comment]
@koskimas when you have time, could you answer these questions, please? ⬆️

**Comment by koskimas** [comment]
> If I just look at those, it seems that you expect .compose to only takes plugins, and .mixin calls to always starts with Model. Is that correct?

Yes. `compose` composes multiple plugins into one. `mixin` applies a bunch of plugins to a model (the first argument) and returns the result. `D = mixin(Model, [A, B, C])` is equivalent to `D = C(B(A(Model)))`

> I don't understand what you mean by "mixin don't take model classes," because every mixin example you have has a Model in the first position. Do you mean you expect them to take Model subclasses?

In your examples, you mixed models with other models. I just meant that that is not possible. All other arguments but the first one, need to be plugins.

> Plugins only accept Model classes, correct?

Yes. Plugin is a function that takes a model class and returns a subclass of the input model class.

> I just looked at the three plugins that you reference in the objection docs, and they don't add to the signatures of the classes they are perturbing. I think the typings could get away with not capturing the plugin signatures, in that case, which would make these types much simpler. Are you ok with that?

I'm absolutely ok with that. Correctly typing plugins could be nasty and would require the plugin developers to create correct kind of typings also.

Sorry for the delay.

**Comment by mceachen** [comment]
I'm going to rebuild this PR based on this new understanding of these methods.

**Comment by mceachen** [comment]
Rebuilt here: https://github.com/Vincit/objection.js/pull/546

**Pull request closed without merging**
