### PR TITLE
Adding ajv-formats package

### PR DESCRIPTION
**Pull request by TigerC10**
Adding the ajv-formats package so people stop complaining about missing date formats.
Solves #2142, #2146, #2147, #2170

### CODE REVIEW

**Comment by LordA98** [comment]
Hi, just wondered if there was any chance of getting this reviewed and merged?

**Comment by vichle** [comment]
@kibertoad Sorry to bother you, I get that you have a lot on your plate, but I saw you have approved and merged other changes. 

This is a fix for an undocumented breaking change that has been in limbo for almost a year, it would be very appreciated if it could be reviewed and merged :pray: 

Sorry for pinging you :heart:

**Comment by lehni** [comment]
This generally looks good, with one caveat:

We either make `ajv-formats` an optional dependency and keep the current `require()` check with the logged message, or we make it a normal dependency and don't need to check if it can be imported. Right now the code does a mixture of both, which isn't so great.

I'd say we just make it a normal dependency and require without checking or complaining.

**Comment by lehni** [comment]
the code is a bit convoluted. Since the PR adds `ajv-formats` as a dependency, the require checks in `getAjvFormats()` aren't needed at all. It can just be imported normally.

**Comment by falkenhawk** [comment]
I agree, it should be a normal dependency. Ajv used to include formats, but they extracted them to a separate package, starting from v7. re: https://github.com/Vincit/objection.js/issues/2146#issuecomment-974137873

**Pull request closed without merging**
