### PR TITLE
feat(knex): add onConflict/ignore/merge for upserts

### PR DESCRIPTION
**Pull request by vvo**
Knex has recently released means to do upserts via ON CONFLICT clauses. I was
able to test it and it works well.

related to: #446 #192 #1406

About this PR: first time here, unsure where and how to add tests though

knex documentation: http://knexjs.org/#Builder-onConflict

### CODE REVIEW

**Comment by kibertoad** [comment]
You probably want to update typings as well: https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts

**Comment by vvo** [comment]
@kibertoad Thanks for the advice, as I am not skilled in Ojbection.js codebase nor TypeScript I hope someone else can give a hand in this PR.

**Comment by willsoto** [comment]
@vvo What would be the best way to help you on this? Do you want me to push directly to your fork (I would need collaborator access) or do you want me suggest things here and work with you to get them implemented?

**Comment by vvo** [comment]
@willsoto just added you as a collaborator, yes feel free to push updates!

**Comment by willsoto** [comment]
@koskimas So one thing that (seems?) to be new to Knex is the concept of "sub-builders." I've been looking around and haven't seen anything in the Objection code base related to this. [Here is a link to the `OnConflictBuilder` class](https://github.com/knex/knex/blob/f953ff4f8f632b9d4e967e6072ac99a3da1e5fbb/lib/query/builder.js#L24-L51) and [here is how it is being used](https://github.com/knex/knex/blob/f953ff4f8f632b9d4e967e6072ac99a3da1e5fbb/lib/query/builder.js#L1119-L1124). 

The current issue is that the [`KnexOperation` class](https://github.com/Vincit/objection.js/blob/bda8e13c90ab00f5a67eab0a3fb050914220308e/lib/queryBuilder/operations/KnexOperation.js#L6-L10) attempts to call through to the `Builder` class, which does not have an `ignore` or `merge`. I imagine the solution here might be to create another `Operation` subclass, but I am not sure I can get access to the Knex builder class returned by `onConflict()` so I can chain `ignore` or `merge` onto it.

Do you have any suggestions?

**Comment by willsoto** [comment]
@vvo just to update you while we wait for an answer, I started writing tests and quickly noticed your implementation wasn't quite working due to the issue I raise above. I'm still committed to getting this merged but I am currently stuck since I am not sure how to proceed.

**Comment by vvo** [comment]
Just in case you endup here and wondering how to do upserts in Knex, you can always do this: https://dev.to/vvo/upserts-in-knex-js-1h4o

**Comment by koskimas** [comment]
Support for onConflict/merge/ignore has been released with objection 2.2.4

**Pull request closed without merging**
