### PR TITLE
Adding tests for PostgreSQL delete returning

### PR DESCRIPTION
**Pull request by newhouse**
I wrote a few tests in what I think is the right spot, but I couldn't verify that they were passing on my local. Received this error:
```
2) integration tests postgres "before all" hook:
     Error: Could not connect to postgres. Make sure the server is running and the database objection_test is created. You can see the test database configurations from file /Users/newhouse/projects/objection.js/testUtils/index.js
```

If that's something I can ignore, then they're probably good?

### CODE REVIEW

**Comment by newhouse** [comment]
@koskimas Let me know if you want me to change anything, or feel free to take over this branch and fix it up!

**Comment by koskimas** [comment]
@newhouse Some tests are failing. [this](http://vincit.github.io/objection.js/#development-setup) may help you to setup the test environment.

**Comment by newhouse** [comment]
Thanks @koskimas looks like they're all passing now. Happy to contribute. When do the doc updates get into the github.io site?

**Comment by koskimas** [comment]
Awesome! Thank you!

**Pull request merged**
